name: Deploy To Live

on:
  push:
    branches: [ release ]

jobs:
  deploy_to_app_engine:
    runs-on: ubuntu-18.04
    name: Deploy to GCP App Engine
    environment: live
    env:
      PROJECT_ID: ${{ secrets.PROJECT_ID }}
      DJANGO_SETTINGS_MODULE: homie.settings.live
      CLOUD_SQL_CONNECTION_NAME: ${{ secrets.CLOUD_SQL_CONNECTION_NAME }}
      LIVE_DB_HOST: '127.0.0.1'
      LIVE_DB_USER: ${{ secrets.DB_USER }}
      LIVE_DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      LIVE_DB_NAME: ${{ secrets.DB_NAME }}
      APP_DB_USER: ${{ secrets.APP_DB_USER }}
      LIVE_DEFAULT_ADMIN_USERNAME: ${{ secrets.DEFAULT_ADMIN_USERNAME }}
      LIVE_DEFAULT_ADMIN_PASSWORD: ${{ secrets.DEFAULT_ADMIN_PASSWORD }}
      LIVE_DJANGO_SECRET: ${{ secrets.DJANGO_SECRET }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.7'
      - name: System check
        shell: bash
        run: |
          ls -alh
          python --version
          pip --version
      - name: Build
        run: |
          pip install -r requirements.txt
          python manage.py collectstatic
      - name: Deploy check
        run: python manage.py check --deploy
      - id: deploy
        name: Deploy
        uses: google-github-actions/deploy-appengine@main
        with:
          project_id: ${{ secrets.PROJECT_ID }}
          credentials: ${{ secrets.GCP_SA_KEY }}
          deliverables: app.live.yaml
      - name: Setup Cloud SQL Proxy
        uses: mattes/gce-cloudsql-proxy-action@v1
        with:
          creds: ${{ secrets.GCP_SA_KEY_JSON }}
          instance: ${{ secrets.CLOUD_SQL_CONNECTION_NAME }}
          proxy_version: 1.20.2
      - name: Migrate DB
        run: python manage.py migrate
      - name: Grant DB privileges
        run: python manage.py grant_db_privileges
      - name: Create a default admin user
        run: python manage.py create_default_admin

  check:
    runs-on: ubuntu-18.04
    name: Check
    environment: live
    needs: deploy_to_app_engine
    steps:
      - name: get_request
        run: curl --fail "${{ secrets.APP_URL }}"
