name: Deploy To Test

on:
  push:
    branches: [ master ]

jobs:
  deploy_to_app_engine:
    runs-on: ubuntu-18.04
    name: Deploy to GCP App Engine
    environment: test
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.7'
      - name: check
        shell: bash
        run: |
          ls -alh
          python --version
          pip --version
      - name: build
        run: |
          pip install -r requirements.txt
          python manage.py collectstatic
      - id: deploy
        name: deploy
        uses: google-github-actions/deploy-appengine@main
        with:
          project_id: ${{ secrets.PROJECT_ID }}
          credentials: ${{ secrets.GCP_SA_KEY }}
          deliverables: app.yaml
      - name: test_deploy
        run: curl "${{ steps.deploy.outputs.url }}"
